### PR TITLE
Formatting code

### PR DESCRIPTION
**Pull request by gchi25**
npm run format - format code with prettier

### CODE REVIEW

**Review by fpigeonjr — COMMENTED** [review]
[prettier](https://prettier.io/) may not like the way this is formatted.
May be a good idea to review the `.prettierrc` and agree on a style there.

**Comment by danny-englander** [comment]
@fpigeonjr Doesn't `npm run format` use the `.prettierrc` in the repo already? What have you been doing up until now if not that?

**Comment by fpigeonjr** [comment]
> @fpigeonjr Doesn't `npm run format` use the `.prettierrc` in the repo already? What have you been doing up until now if not that?

Yes sorry, `npm run format` will run prettier vs the whole project except files that are in the `.prettierignore`. 
I have been using vscode and have the prettier extension installed and set to format on save.

**Comment by scottqueen-bixal** [comment]
closing

**Pull request closed without merging**
