### PR TITLE
797 remove unused content

### PR DESCRIPTION
**Pull request by scottqueen-bixal**
## PR Summary

This work does two things:
1. removes unused content for the following paths

```
/becoming-a-parent
/financial-hardship
/school-and-education
/military-service
/national-emergency-and-disaster
/types
/agencies
```

2. dynamically generates i18n based routes in sitemap

Since we no longer have this content in the site the pages and routes do not get generated.  Accessing these routes would return a 404.  This also means that we can now successfully generate a sitemap dynamically.

## Related Github Issue

- fixes #(issue)

## Type of change

Please delete options that are not relevant.

- [x] Task
- [ ] Bug fix
- [ ] New feature
- [ ] This change requires a documentation update

## Branch Name

The name of this branch

## Testing environment

Link to a Federalist URL or to be tested on local dev environment.

## Detailed Testing steps

Link to testing steps in the issue or list them here:

Code review @gchi25 
- [ ] review configuration of sitemap gen to ensure it is dynamically outputting the expected asset

Analytics review @nickpistone 
- [ ] review sitemap and ensure the new i18n output is as expected for site indexing

e2e review @nehemiah-abuga 
- [x] write 2-3 test for each of our life-benefits that creates a string of query parameters on production that can be used for manual QA on the test env

```
/death-of-a-loved-one
/disability
/retirement
```

content review @diegocob 
- [ ] ensure that any content from our removal list results in "Page not found"
- [ ] manual QA to ensure we haven't missed any content that needs to be unpublished

etc...

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by gchi25 — CHANGES_REQUESTED** [review]
No links of Spanish version of life events.
https://benefits-tool.usa.gov/preview/gsa/usagov-benefits-eligibility/797-remove-unused-content/death-of-a-loved-one
https://benefits-tool.usa.gov/preview/gsa/usagov-benefits-eligibility/797-remove-unused-content/disability
https://benefits-tool.usa.gov/preview/gsa/usagov-benefits-eligibility/797-remove-unused-content/retirement
https://benefits-tool.usa.gov/preview/gsa/usagov-benefits-eligibility/797-remove-unused-content/es
https://benefits-tool.usa.gov/preview/gsa/usagov-benefits-eligibility/797-remove-unused-content/

**Comment by scottqueen-bixal** [comment]
> No links of Spanish version of life events

With multilingual we should have hreflang attributes for root paths that link to all the other routes

**Review by gchi25 — APPROVED** [review]

**Review by nehemiah-abuga — APPROVED** [review]
I have validated that the removed unused content didn't impact the functionality of the site. Compared with production and everything is looking good. Approved

**Comment by nickpistone** [comment]
XML file matches with current site structure and removes unused content. After deployment, I will submit the sitemap to Search Console and review and QA that way.[XML file](https://federalist-edd11e6f-8be2-4dc2-a85e-1782e0bcb08e.sites.pages.cloud.gov/preview/gsa/usagov-benefits-eligibility/797-remove-unused-content/sitemap.xml)

**Review by nickpistone — APPROVED** [review]

**Pull request merged**
