### PR TITLE
777 mobile menu styles

### LINKED ISSUE #777: Matching Mobile Navigation Menu to the Desktop
**Matching Mobile Navigation Menu to the Desktop Navigation Menu**, 
Currently they look different

Was decided previously that the mobile navigation to match usa.gov is a big effort. This is not a priority for v1. 

We do not have a requirement outline for the content menu on the mobile navigation, this also isn't required/needed. Will track communications in this Issue here. 

Our application on the left, (https://www.usa.gov/government-death-benefits) where the entrance to our benefit locator get's linked on right
Image

### PR DESCRIPTION
**Pull request by scottqueen-bixal**
## PR Summary

This work takes navigation items from the primary and secondary menu and styles them in a mobile menu presentation with the same look and feel as usa.gov.

Screenshot 2023-05-10 095303

Known differences:
- no nested menu navigation
- no active menu items
- gov contact number retains the language "Call us at 1-844-USAGOV1" and its translation

## Related Github Issue

- fixes #777

## Type of change

Please delete options that are not relevant.

- [x] Task
- [ ] Bug fix
- [ ] New feature
- [ ] This change requires a documentation update

## Detailed Testing steps

Link to testing steps in the issue or list them here:

- [x] navigate to feature branch test env
- [ ] set window into responsive view
- [ ] set dimensions to 1023 x 720
- [ ] open a new browser window and set up [usa.gov](https://www.usa.gov/government-death-benefits) is the same way
- [ ] compare visual alignment between the two menus

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by fongcindy — APPROVED** [review]
This LGTM, thanks Scott!

**Review by nehemiah-abuga — CHANGES_REQUESTED** [review]
When you expand the USA banner header accordion, the language switcher button is blocking the content and it is located on the right top vs it being at the bottom right of header section. Also the content between the USA gov expanded banner header is different than what we have on the live site

Look on this branch
image

Live Site (usa.gov)
image

**Comment by scottqueen-bixal** [comment]
@nehemiah-abuga I've updated the position of our language-switcher at mobile, can you make another pass at QA with this changes.


https://github.com/GSA/usagov-benefits-eligibility/assets/37077057/b8abe32e-b94c-4833-809d-e33f9d57d136

**Review by nehemiah-abuga — APPROVED** [review]
I have verified that the language switcher is aligned correctly similar to USA gov. This issue has been resolved

image

**Pull request merged**
