### PR TITLE
QA & A11Y on multi-life-event-2023-content branch

### LINKED ISSUE #729: QA Testing on Multi-life-events
### Description

Completed the content commits on the three multi life events pages. Need QA & a11y testing.

### User Story

Need to confirm that the multi life events pages are running well.

### Architectural Decision Records (ADRs)

_No response_

### PR DESCRIPTION
**Pull request by diegocob**
Test QA and A11Y on the multi-life-event-2023-content branch with added and edited content in EN & ES:
1. Death of a Loved one
2. Disability 
3. Retirement 

## Related Github Issue

- fixes #729

## Type of change

- [ ] QA
- [ ] Bug fix
- [ ] A11Y
- [ ] Content revision

## Branch Name

multi-life-event-2023-content

## Testing environment

- [ ] DOLO: https://federalist-edd11e6f-8be2-4dc2-a85e-1782e0bcb08e.sites.pages.cloud.gov/preview/gsa/usagov-benefits-eligibility/multi-life-event-2023-content/death-of-a-loved-one/?
- [ ] Disability: https://federalist-edd11e6f-8be2-4dc2-a85e-1782e0bcb08e.sites.pages.cloud.gov/preview/gsa/usagov-benefits-eligibility/multi-life-event-2023-content/disability/?
- [ ] Retirement: https://federalist-edd11e6f-8be2-4dc2-a85e-1782e0bcb08e.sites.pages.cloud.gov/preview/gsa/usagov-benefits-eligibility/multi-life-event-2023-content/retirement/?

## Detailed Testing steps

Link to testing steps in the issue or list them here:

- [ ] Test DOLO in EN
- [ ] Test DOLO in ES
- [ ] Test Disability in EN
- [ ] Test Disability in ES
- [ ] Test Retirement in EN
- [ ] Test Retirement in ES

## Checklist:

Not sure if this applies...

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Review by nehemiah-abuga — APPROVED** [review]
I have reviewed the changes and compared with the website. This look good. Approved

**Review by nehemiah-abuga — APPROVED** [review]
I have verified this change and it looks good

image

**Comment by diegocob** [comment]
Hi @amycole501, 
Could you please have an a11y look at the following things of the multi-life-event pages on [federalist content site](https://federalist-edd11e6f-8be2-4dc2-a85e-1782e0bcb08e.sites.pages.cloud.gov/preview/gsa/usagov-benefits-eligibility/multi-life-event-2023-content/death-of-a-loved-one/?):

1. Subheading: A11Y check if the new subheading below the title of each page ("Life experiences can be stressful. Finding benefits shouldn’t be. Learn about potential Federal benefits in one place.") reads well in all life experiences for ES and EN:

Subtitle

- [ ] DOLO EN
- [ ] DOLO ES
- [ ] Retirement EN
- [ ] Retirement ES
- [ ] Disability EN
- [ ] Disability ES

3. A11y check so the new critical information field reads well in EN and ES

Critical info field

- [ ] a11y in EN
- [ ] a11y in ES

**Comment by amycole501** [comment]
The "life expectancy" text is great and reads well below the required levels.
The "SSA benefits" line is fine however uses passive voice. One possible edit: "You only need to apply once for all SSA benefits." 
I did do a check for accessibility in a translation tool and I believe it passes. The grade level and grammar appear to pass accessibility checks despite my rusty Spanish.

**Comment by amycole501** [comment]
Updating this to say that the wording is fine as-is and due to the technical nature and specificity of the wording the SSA verbiage is good to go.

**Comment by diegocob** [comment]
Critical information application field text not showing up for:
	1. dod-retirement-and-disability-payments, Concurrent Retirement and Disability Payments (CRDP)
	2. /locales/en/benefits/dod-thrift-savings-plan.json: Thrift Savings Plan
	3. locales/en/benefits/dod-special-compensation.json: Division of Coal Mine Workers' Compensation (Black Lung Benefits)
locales/en/benefits/cms-medicare-savings-programs.json

Still going through the checks, will continue in the morning 04/26.

**Comment by scottqueen-bixal** [comment]
> Critical information application field text not showing up for: 1. dod-retirement-and-disability-payments, Concurrent Retirement and Disability Payments (CRDP) 2. /locales/en/benefits/dod-thrift-savings-plan.json: Thrift Savings Plan 3. locales/en/benefits/dod-special-compensation.json: Division of Coal Mine Workers' Compensation (Black Lung Benefits) locales/en/benefits/cms-medicare-savings-programs.json
> 
> Still going through the checks, will continue in the morning 04/26.

@diegocob it looks like some of the markdown files are missing the required keys and dot notation value pairs.

for example: https://github.com/GSA/usagov-benefits-eligibility/blob/multi-life-event-2023-content/content/benefits/dod-retirement-and-disability-payments.md?plain=1#L16-L17

should include 

`criticalApplicationInformation: dod-retirement-and-disability-payments.criticalApplicationInformation`

similar to how we see it in other markdown files, ie https://github.com/GSA/usagov-benefits-eligibility/blob/multi-life-event-2023-content/content/benefits/ssa-disability-insurance-child-disabled.md?plain=1#L14-L15

if you navigate to https://github.com/GSA/usagov-benefits-eligibility/tree/multi-life-event-2023-content/content/benefits you can see commit messages related to #254 

This could be a good place to start for checking what has already been updated vs what remains to get those fields to appear as expected.

**Pull request merged**
