### PR TITLE
#610 Fix DOM - Safari does not update

### PR DESCRIPTION
**Pull request by gchi25**
Fix issue of "COVID-19 Funeral Assistance: DOM in Safari does not update when The deceased's funeral/burial date is on or after 01/21/2020".

## Testing
Test on this branch, `610-safari-date`

### CODE REVIEW

**Comment by danny-englander** [comment]
@nehemiah-abuga Can you test this one? See _How to replicate_  on #610 for testing steps.

**Review by danny-englander — COMMENTED** [review]
This looks good to me, I tested locally and all works fine. Handing off to @nehemiah-abuga for testing.

**Review by nehemiah-abuga — APPROVED** [review]
I have reviewed this locally and it works as expected.

**Review by danny-englander — APPROVED** [review]
I have reviewed locally and this works great now.

**Pull request merged**
